### ISSUE TITLE
Icons occasionally missing when using exploding d10s

### ISSUE THREAD

**Issue by Sandvich** [JohanFalt/Foundry_WoD20#700] opened 2023-08-16 20:28 UTC
**Have you tested without modules**
No, we'll try this if we can't pin it down easily.

**Describe the bug**
When using exploding d10s (I'm not sure if that causes it or not), the dice icons sometimes don't show up. It seems to be semi-random which icons are broken.

**To Reproduce**
1. Turn on exploding d10s
2. Roll a bunch of d10s
3. If a 10 is rolled, there will be some broken images

**Screenshots**
![10_error](https://github.com/JohanFalt/Foundry_WoD20/assets/5482185/99477c36-87f5-48f4-80d6-b204e1175fb9)

**Versions of software:**
- Foundry v11 stable, build 370
- WoD 3.1.10

**Comment by JohanFalt** [comment] 2023-08-17 06:52
I can't reproduce this.

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/accb1b47-e9cc-4103-84e9-b8130ec36161)

What settings have you entered? Can you make a screenshot of that?

**Comment by JohanFalt** [comment] 2023-08-17 07:14
This was a tricky one. Problem was that it only happened on the first roll and it was a collision with the Changeling roll rules. Fixed will be part of 3.1.11. Thank you for the help.

**Closed by JohanFalt** 2023-08-17 07:14 UTC
Labels: Bug, Done, GUI

**Comment by Sandvich** [comment] 2023-08-17 07:32
Woah, that was fast, I was planning to go through in detail at the weekend to get you more info. Thanks for the quick fix!
